language: go

notifications:
  email:
    on_success: never
    on_failure: always

go:
  - "1.13.x"

env:
  global:
    - DEBUG=true
    - TEST_REDIS_ADDR='127.0.0.1:6379'
    - CODECOV_TOKEN="0bf6ff38-02b7-4d65-9fdf-bbf3bb56c327"

services:
  - redis-server

install:
  - go mod download

script:
  - make ci-test

after_success:
  - bash <(curl -s https://codecov.io/bash)
